
#' Read in a text file generated by Eprime
#'
#' @param filename Either the full or relative path to the .txt file that is to
#'   be parsed.
#' @return Each line of the file is stored and returned in a character vector.
#'
#' @details The encoding on an Eprime txt file should be UCS-2 Little Endian,
#'   but sometimes this is not the case. We delegate the fussy encoding details
#'   to the \code{stringi::str_read_lines} function.
#'
#' @importFrom stringi stri_read_lines
#' @importFrom tools file_path_sans_ext
#' @export
read_eprime <- function(filename) {
  require("tools")
  require("stringi")
  basename <- file_path_sans_ext(basename(filename))
  eprime_log <- stri_read_lines(filename)
  attr(eprime_log, "basename") <- basename
  eprime_log
}

